import type { DashboardSnapshot, SkillDraft } from '../contracts/index.js'
import type { AnyRecord } from './api.js'

/** In-memory fixtures for the explicitly enabled local preview only. */
export function createPreviewApi(emptyDashboard: DashboardSnapshot): AnyRecord {
  const memory: AnyRecord = { skills: [], evaluations: [], scenarios: [], traces: [], releases: [], jobs: [] }
  const now = () => new Date().toISOString()
  const skill = (input: AnyRecord = {}): SkillDraft => {
    const title = String(input.title || '省级报表异常判断')
    return { skillId: input.skillId || `skill_preview_${memory.skills.length + 1}`, title, description: String(input.description || '识别业务报表中的异常并给出可审计结论。'), authority: 'province', files: { 'SKILL.md': String(input.files?.['SKILL.md'] || `# ${title}\n\n- 检查 report_cycle\n- 检查 province_code\n- 输出可追溯的判断依据`), 'manifest.yaml': String(input.files?.['manifest.yaml'] || `name: ${title}\nrequired_facts: [report_cycle, province_code]`), 'rules/decision-tree.yaml': String(input.files?.['rules/decision-tree.yaml'] || 'version: 1\nroot: start') }, source: { kind: 'blank' }, draftVersion: 1, contentHash: 'preview', status: 'draft', createdAt: now(), updatedAt: now() }
  }
  const dashboard = (): DashboardSnapshot => ({ ...emptyDashboard, status: memory.skills.length ? 'ready' : 'empty', counts: { activeSkills: memory.skills.length, publishedSkills: memory.releases.length, publishReadySkills: 0, pendingEvaluations: memory.evaluations.filter((item: any) => item.status !== 'completed').length, unmeasuredSkills: memory.skills.filter((item: AnyRecord) => !memory.evaluations.some((evaluation: AnyRecord) => evaluation.skillId === item.skillId && evaluation.status === 'completed')).length, traces24h: memory.traces.length, releaseChanges30d: memory.releases.length }, generatedAt: now(), sections: emptyDashboard.sections.map(section => ({ ...section, status: memory.skills.length ? 'ready' : 'empty', items: section.id === 'skills' ? memory.skills.map((item: AnyRecord) => ({ id: item.skillId, title: item.title, detail: 'draft · 1 次编辑', action: 'skill' })) : [] })) })
  const findEvaluation = (id: string) => memory.evaluations.find((item: AnyRecord) => item.evaluationId === id)
  return {
    dashboardGet: async () => dashboard(),
    skillList: async () => ({ status: 'ready', skills: memory.skills }),
    skillGet: async (id: string) => ({ status: 'ready', skill: memory.skills.find((item: AnyRecord) => item.skillId === id) }),
    skillCreate: async (_op: string, input: AnyRecord) => { const item = skill(input); memory.skills.unshift(item); return { status: 'saved', skill: item } },
    skillSave: async (_op: string, input: AnyRecord) => { const index = memory.skills.findIndex((item: AnyRecord) => item.skillId === input.skillId); const item = { ...memory.skills[index], ...input.patch, files: { ...memory.skills[index].files, ...input.patch?.files }, draftVersion: (memory.skills[index].draftVersion || 0) + 1, updatedAt: now() }; memory.skills[index] = item; return { status: 'saved', skill: item } },
    skillValidate: async (id: string) => ({ status: 'passed', validation: { status: 'passed', errors: [], checkedAt: now(), contentHash: memory.skills.find((item: AnyRecord) => item.skillId === id)?.contentHash || '' } }),
    evaluationList: async () => ({ status: 'ready', evaluations: memory.evaluations }),
    evaluationGet: async (id: string) => ({ status: 'ready', evaluation: memory.evaluations.find((item: AnyRecord) => item.evaluationId === id) }),
    evaluationCreate: async (_op: string, input: AnyRecord) => { const item = { evaluationId: `eval_preview_${memory.evaluations.length + 1}`, skillId: input.skillId, snapshotHash: 'preview', executionProfile: { provider: 'preview', model: 'preview' }, cases: (input.cases || []).map((testCase: AnyRecord) => ({ ...testCase })), status: 'pending', createdAt: now(), updatedAt: now() }; memory.evaluations.unshift(item); return { status: 'saved', evaluation: item } },
    evaluationRun: async (_op: string, input: AnyRecord) => { const item = findEvaluation(input.evaluationId); if (!item) throw new Error('preview evaluation not found'); item.cases = item.cases.map((testCase: AnyRecord) => ({ ...testCase, actual: testCase.expected === undefined ? { verdict: 'pass' } : JSON.parse(JSON.stringify(testCase.expected)), grade: 'correct' })); item.accuracy = { numerator: item.cases.length, denominator: item.cases.length, value: item.cases.length ? 1 : 0 }; item.status = 'completed'; item.updatedAt = now(); return { status: 'queued', evaluation: item, job: { jobId: `job_${item.evaluationId}`, status: 'completed' } } },
    evaluationAnnotate: async (_op: string, input: AnyRecord) => { const item = findEvaluation(input.evaluationId); if (!item) throw new Error('preview evaluation not found'); item.cases = item.cases.map((testCase: AnyRecord) => testCase.caseId === input.caseId ? { ...testCase, grade: input.grade } : testCase); const judged = item.cases.filter((testCase: AnyRecord) => ['correct', 'incorrect'].includes(testCase.grade)); item.accuracy = { numerator: judged.filter((testCase: AnyRecord) => testCase.grade === 'correct').length, denominator: judged.length, value: judged.length ? judged.filter((testCase: AnyRecord) => testCase.grade === 'correct').length / judged.length : 0 }; item.updatedAt = now(); return { status: 'saved', evaluation: item } },
    evaluationOptimize: async () => ({ status: 'empty', suggestions: [] }),
    releaseCheck: async (id: string) => { const skill = memory.skills.find((item: AnyRecord) => item.skillId === id); const evaluation = memory.evaluations.find((item: AnyRecord) => item.skillId === id && item.status === 'completed'); return { status: skill && evaluation ? 'ready' : 'blocked', skillId: id, checks: { validation: { status: 'passed', errors: [] }, evaluation: evaluation || null, scenarios: [] } } },
    releasePublish: async (_op: string, input: AnyRecord) => { const release = { releaseId: `release_preview_${memory.releases.length + 1}`, skillId: input.skillId, version: `v${memory.releases.length + 1}`, contentHash: 'preview', createdAt: now() }; memory.releases.unshift(release); return { status: 'published', release, runtime: { status: 'pending-load-confirmation', releaseId: release.releaseId } } },
    traceList: async () => ({ status: memory.traces.length ? 'ready' : 'empty', traces: memory.traces }),
    traceGet: async (id: string) => memory.traces.find((item: AnyRecord) => item.traceId === id),
    traceProtect: async (_op: string, input: AnyRecord) => ({ status: 'saved', traceId: input.traceId, protectedUntil: now() }),
    traceRetain: async (_op: string, input: AnyRecord) => ({ status: 'saved', traceId: input.traceId, retainedUntil: now() }),
    traceClear: async (_op: string, input: AnyRecord) => { memory.traces = memory.traces.filter((item: AnyRecord) => item.traceId !== input.traceId); return { status: 'cleared', traceId: input.traceId } },
    scenarioList: async () => ({ status: 'ready', scenarios: memory.scenarios }),
    scenarioCreate: async (_op: string, input: AnyRecord) => { const scenario = { scenarioId: `scenario_preview_${memory.scenarios.length + 1}`, name: input.name, region: input.region, description: input.description || '', skillIds: input.skillIds || [], samples: [], rules: [], status: 'draft', updatedAt: now() }; memory.scenarios.unshift(scenario); return { status: 'saved', scenario } },
    scenarioSave: async (_op: string, input: AnyRecord) => { const existing = memory.scenarios.find((item: AnyRecord) => item.scenarioId === input.scenarioId); const scenario = existing ? Object.assign(existing, input, { updatedAt: now() }) : { ...input, scenarioId: input.scenarioId || `scenario_preview_${memory.scenarios.length + 1}`, samples: input.samples || [], rules: input.rules || [], skillIds: input.skillIds || [], status: input.status || 'draft', updatedAt: now() }; if (!existing) memory.scenarios.unshift(scenario); return { status: 'saved', scenario } },
    scenarioAddSample: async (_op: string, input: AnyRecord) => { const scenario = memory.scenarios.find((item: AnyRecord) => item.scenarioId === input.scenarioId); if (!scenario) throw new Error('preview scenario not found'); scenario.samples.push({ sampleId: `sample_preview_${scenario.samples.length + 1}`, filename: input.filename || 'sample.json', headers: Object.keys(input.rows?.[0] || {}), rows: input.rows || [], sourceRegions: [], createdAt: now() }); return { status: 'saved', scenario } },
    excelRuleGenerate: async (_op: string, input: AnyRecord) => { const scenario = memory.scenarios.find((item: AnyRecord) => item.scenarioId === input.scenarioId); if (!scenario || !scenario.samples.length) throw new Error('preview sample required'); const sample = scenario.samples[0]; const rule = { ruleId: `rule_preview_${scenario.rules.length + 1}`, version: scenario.rules.length + 1, region: scenario.region, scenarioId: scenario.scenarioId, canonicalFields: sample.headers, requiredFacts: sample.headers, layouts: [{ layoutId: `layout_preview_${scenario.rules.length + 1}`, headers: sample.headers, mapping: Object.fromEntries(sample.headers.map((header: string) => [header, header])) }], status: 'candidate', createdAt: now(), updatedAt: now() }; scenario.rules.push(rule); return { status: 'candidate', rule, scenario } },
    excelRuleConfirm: async (_op: string, input: AnyRecord) => { const scenario = memory.scenarios.find((item: AnyRecord) => item.scenarioId === input.scenarioId); const rule = scenario?.rules.find((item: AnyRecord) => item.ruleId === input.ruleId); if (!rule) throw new Error('preview rule not found'); rule.status = input.publish ? 'published' : 'confirmed'; return { status: input.publish ? 'published' : 'saved', rule, scenario } },
    excelRuleRegression: async (id: string) => ({ status: memory.scenarios.find((item: AnyRecord) => item.scenarioId === id)?.rules.length ? 'passed' : 'blocked', results: [] }),
    settingsGet: async () => ({ status: 'ready', config: { dataDir: 'preview', managerPath: 'preview/manager.sqlite', runtimePath: 'preview/runtime.sqlite', otlpPort: 4319 }, settings: {} }),
    settingsHealth: async () => ({ status: 'healthy', schemaVersion: 2, manager: { integrity_check: 'ok' }, runtime: { integrity_check: 'ok' } }),
    settingsBackup: async () => ({ status: 'ready', backupId: `preview-${Date.now()}`, files: ['manager.sqlite', 'runtime.sqlite'] }),
  }
}
